Feature/drag and drop table
calumtomeny/quiz-master pull request #189
Opened 2021-05-13 14:12 UTC by timloudon

Closes issue #113

2021-05-13 14:15 UTC, timloudon commented
Not exactly sure why the package-lock.json file is in there, nor why it is all edited.

Also, I think I could probably structure this feature more clearly although I'm not sure what the best approach would be. Comments welcome.

2021-05-13 21:36 UTC, calumtomeny commented on quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionCreator.tsx
> +      return;
Is this indentation right?

2021-05-13 21:49 UTC, calumtomeny requested changes
Great addition to the app!

2021-05-13 21:49 UTC, calumtomeny commented on quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionCreator.tsx
> +                      i={i}
You might want to give these better names.

2021-05-13 21:49 UTC, calumtomeny commented on quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/Question.tsx
> +      <Draggable draggableId={props.x.number.toString()} index={props.i}>
You might want to split this into multiple components.

2021-05-14 23:07 UTC, calumtomeny approved these changes

2021-05-14 23:07 UTC, merged